[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./deployments" }]
ffi = true

# Enhanced testing configuration
fuzz = { runs = 1000 }
invariant = { runs = 500, depth = 15 }

# Gas reporting
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
